---
title: "Untitled"
format: html
editor: source
editor_options: 
  chunk_output_type: console
---

```{r}

library(dplyr)
library(tidyr)
library(readr)
library(skimr)
library(stringr)
library(ggplot2)
```


# Data import



# Data tidying


https://speciationgenomics.github.io/data_visualisation_handling/

```{r}

starwars %>% 
  select(name, homeworld)

starwars %>% 
  select(-name)

starwars %>% 
  select(name:homeworld)

starwars %>% 
  select(name:mass, homeworld)

starwars %>% 
  select(name, ends_with("color"))

starwars %>% 
  select(name, starts_with("s")) 



```


```{r}

starwars %>% 
  filter(species == "Human")

starwars %>% 
  filter(species == "Human",  homeworld == "Tatooine")

starwars %>% 
  filter(species == "Human" |  homeworld == "Tatooine")

```


```{r}

starwars %>% 
  arrange(desc(mass))

```


```{r}

starwars %>% 
  mutate(name, bmi = mass / ((height / 100)  ^ 2)) %>%
  select(name:mass, bmi)

```


```{r}

starwars %>%
  group_by(species) %>%
  summarise(
    n = n(),
    mass = mean(mass, na.rm = TRUE)
  ) %>%
  filter(n > 1)

```

```{r}

```




```{r}
starwars %>% group_by(species) %>% tally()

starwars %>% count(species)

```



# Data transformation



# Data visualisation

# Data communication

# Codebook

```{r}

data_city
  skim()

codebook_city %>% 
  count(measurement)

```


